Add combinatorial example for a recursive structure.
astynax/tea-combine pull request #3
Opened 2020-10-05 20:42 UTC by Heimdell

An example for a recursive tree, adapted from #1 .

Fixes #2 .

2020-10-05 21:35 UTC, Heimdell commented
The idea is to add type variables for components containing aggregation root, so they loose cyclic dependency, and can be moved to separate file.

Of course, their `view` and `update` have to get additional parameter for root `view`/`update`.

I tried to pull that example apart to one-file-per-component, but I'm unable to convince `elm reactor` that the new directory I create should be in the import path, even if I add it to `elm.json:"source-directories"`.

2020-10-06 06:23 UTC, astynax requested changes

2020-10-06 06:23 UTC, astynax commented on src/TeaCombine.elm
> +    , viewBoth, viewAll, viewEach, viewSome, viewEvery
Every exposed function should be mentioned in the module's docstring, or else package builder will deny the build.

2020-10-06 06:23 UTC, astynax commented on src/TeaCombine/Pure/Many.elm
> +updateOfGivenIndex :
`updateByIndex`?

2020-10-06 06:23 UTC, astynax commented on src/TeaCombine.elm
> +viewEvery :
This is no a "View" because it doesn't return `Html`. It think what "previewEvery" will be less confusing.

2020-10-06 06:23 UTC, astynax commented on examples/pure/Combinatorial.elm
> +type alias Counter = Int
In other examples in this folder I used a separate `Counter` "component". This separation keeps the main module clean and shows an actual code reusing. Can you combine same Counter in your example?

2020-10-06 06:23 UTC, astynax commented on examples/pure/Combinatorial.elm
> +import TeaCombine.Pure.Many as Many
I not so in to this idea of module aliasing. There is no such stuff in other examples and I prefer to keep the consistency.

2020-10-06 06:23 UTC, astynax commented on examples/pure/Combinatorial.elm
> +withTree : ((Forest Tree, Int) -> (Forest Tree, Int)) -> Tree -> Tree
This explicit tuples are abstraction leaks. All the types designed to be infered not handcrafted. That's why you can not see any type annotation for combined views or updates: in any more or less complicated case an any type will look like a unreadable mess - in Elm we don't have a type operators so *combinations of types* can not be composed in same manner as the values. And too complicated types in examples are making those examples difficult to grock.

2020-10-06 06:23 UTC, astynax commented on examples/pure/Combinatorial.elm
> +type Msg = Msg (Either (Tea.Ix Msg) Inc)
Same problem here: you shouldn't annotate resulting combination (see a comment above).

2020-10-06 06:23 UTC, astynax commented on examples/pure/Combinatorial.elm
> +unMsg (Msg msg) = msg
Such auxiliary functions pollute the rool level. Make them local or at least move under the "main" code and explicitly mark as helpers.

2020-10-06 06:23 UTC, astynax commented on examples/pure/Combinatorial.elm
> +            ]
A simple local shortcut will make this example way more approachable! Something like this
```elm
let node v cs = Node ...
in node 0
    [ node 1 []
    , node 2
        [ node 3 []
        ]
    ]
```

2020-10-06 06:23 UTC, astynax commented on examples/pure/Combinatorial.elm
> +    <| div [] [ header, contents ]
I see what you didn't apply the `elm-format`. But you should.

2020-10-06 06:23 UTC, astynax commented on examples/pure/Combinatorial.elm
> +    = Node (Forest Tree, Int)
All the purpose of that example is to show what you **don't need** to define a tree type and all you need is combinators! No auxiliary types should be defined here,

2020-10-06 06:32 UTC, astynax commented
And take a look at [this](https://github.com/astynax/tea-combine/blob/master/examples/pure/Main.elm#L21) "inspector". Maybe it will be fun to add such visualization to the demo.

2020-10-06 06:50 UTC, Heimdell commented on examples/pure/Combinatorial.elm
> +    = Node (Forest Tree, Int)
This will end with Elm writing some type expression with `∞` and refusing the code. But I'll try. I'd like to have a
`newtype Fix f = Fix { unFix :: f (Fix f) }` here.

2020-10-06 07:07 UTC, astynax commented
Can you rename `Combinatorial` to `Recursive`? All the examples here *are* combinatorial but only this new one is recursive :)

2020-10-06 07:46 UTC, astynax commented on examples/pure/Combinatorial.elm
> +    = Node (Forest Tree, Int)
You can't define types like this in Elm because it hasn't HKT.

2020-10-06 08:10 UTC, Heimdell commented on examples/pure/Combinatorial.elm
> +    = Node (Forest Tree, Int)
I [know](https://github.com/elm/compiler/issues/965).

Therefore I have to leave it be an opaque type.

2020-10-06 09:50 UTC, astynax commented on examples/pure/Recursive.elm
> +    = Node ( Counter.Model, Forest.Model Tree )
[Here is](https://github.com/astynax/tea-combine/blob/master/src/TeaCombine.elm#L39) an alias for such cases. All the API functions are using this alias instead of `(,)`. So it will be nice to have a type
```elm
type Tree
    = Node (Both Counter.Model Forest.Model Tree)
```
for the sake of consistency :)

2020-10-06 11:13 UTC, astynax commented
LGTM :+1:

2020-10-06 11:13 UTC, astynax approved these changes

2020-10-06 11:13 UTC, merged